name: json_annotation_tools_example
description: Example showing @SafeJsonParsing() code generation with enhanced error messages.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  json_annotation: ^4.9.0
  json_annotation_tools:
    path: ../

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
