# Build configuration for json_annotation_tools code generation
# This file configures the @SafeJsonParsing annotation generator

builders:
  safe_json_parsing:
    import: "package:json_annotation_tools/generator.dart"
    builder_factories: ["safeJsonParsingBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
