name: test_code_generation
description: Test project for @SafeJsonParsing() code generation
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_annotation_tools:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
